# Generated by Django 3.2.5 on 2021-07-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MixerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcAddress', models.CharField(blank=True, default='', max_length=50)),
                ('destAddress', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='created', max_length=50)),
            ],
        ),
    ]
