# Generated by Django 3.2.5 on 2021-07-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixerrequest',
            old_name='destAddress',
            new_name='deposit_address',
        ),
        migrations.RenameField(
            model_name='mixerrequest',
            old_name='srcAddress',
            new_name='dest_address',
        ),
        migrations.AddField(
            model_name='mixerrequest',
            name='src_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
