# Generated by Django 3.2.5 on 2021-07-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_auto_20210722_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixerrequest',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=50),
        ),
    ]
