# Generated by Django 3.1.6 on 2021-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_auto_20210722_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixerrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
