# Generated by Django 3.2.5 on 2021-07-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0003_alter_mixerrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixerrequest',
            name='dest_address_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mixerrequest',
            name='dest_address_3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mixerrequest',
            name='dest_address_4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mixerrequest',
            name='dest_address_5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
